services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumption-tracker-api
    volumes:
      - ../src:/var/www/html/api # Mountuje src/ složku
    networks:
      - consumption-tracker-network

  nginx:
    image: nginx:latest
    container_name: consumption-tracker-api-nginx
    ports:
      - "3010:80"
      - "3443:443"
    volumes:
      - ../src:/var/www/html # Mountuje src/ složku
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certificates:/etc/nginx/certificates:ro
    depends_on:
      - app
    networks:
      - consumption-tracker-network

  db:
    image: mysql:8.0
    container_name: consumption-tracker-api-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: consumptions
      MYSQL_USER: trackeruser
      MYSQL_PASSWORD: trackerpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - consumption-tracker-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: consumption-tracker-api-phpmyadmin
    restart: always
    ports:
      - "3015:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

networks:
  consumption-tracker-network:
    driver: bridge

volumes:
  db_data:
